language: node_js
addons:
  sonarcloud:
    organization: loopingz-github
node_js:
- '10'
script:
- npm run test
after_success:
- sonar-scanner
before_deploy:
- npm run build
deploy:
  provider: npm
  email: rcattiau@loopingz.com
  skip_cleanup: true
  tag: next
  on:
    tags: true
  api_key:
    secure: x6bTr1eHLmhQmSiqjJ9vk5dHB+z2qtB0HSLwydnrJhHIqW0YlPyhXjZJ5RZUqdYX/yTSFFypIK3hSDTeY6iiyJqtM/txCmC7oQxnbnNtMHpTT64XWaKXEDqxI8oIWepHrHWlgDgv1cQ62MMb/4IHwA9Sd+RIXR6KZudSP7y0QZRDzlI357KGh/PN41domKktOauO2K1EQ5Kb/iGG4nyoimXsX50I8xnXIFw2xAvkdKsWJuFVY6YvyTY94hwcBjYofifJQuLoyLUF+9TBBwIOmyvhsYkly9rY19ROYRFNQG6JGyCJVHDpfyNGmAxwE13VwxypSmLwDMZAQnIcpqvvtk1+c3kGgzI/YaFLpWhxTc0gu4DXvmmoe8zokAI6UnMrRGdugmLtvY3X5dUw9cl7ahNs12E/PC5CQ8djGO1GRgnOamxJOhu9xsxqGcOuzT7DGo9ArcjwvGLRAPZeMDIhuMZ5lPNAH7xBm7h/yni33Nh7QO/GmG/DNIYr3GCn95aqbrMoq36NgaQN/NsCIziwG7YbdA5jZKIRMWmcuIJ0CgNRdJquBnx8zcQO6KlZKuNO0/UXkTPnu+bfT0lf1B9qCbROCmb5e+Zb8HuskhY5DDUE5+jk5hFT+IoC5bGMN6V1lNwJ8tP/O2/DfzANZeWA+nDMfuBSqMhHGKpuUOkVo2M=
